name: basiq-php-api
services:
  myservice:
    type: php:8.1
    via: cli
    xdebug: "debug,develop"
    composer_version: 2
    overrides:
      environment:
        XDEBUG_CONFIG: "idekey=PHPSTORM serverName=BASIQPHPAPIPHPSTORM discover_client_host=0 client_host=192.168.0.245"
    run_as_root:
      # Install netcat package to provide the nc command.
      # This way we can check that we can connect to the  XDEBUG client port using this command:
      # `nc -zv <your host IP> <the client xdebug port> && echo "Port is open" || echo "Port is closed"`
      - apt-get update -y && apt-get install -y netcat
tooling:
  php:
    service: myservice
  composer:
    service: myservice
