<?php
/**
 * ConnectorAuthorizationMeta
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Core
 *
 * All included utility endpoints for Basiq partners
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ConnectorAuthorizationMeta Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ConnectorAuthorizationMeta implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ConnectorAuthorizationMeta';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'forgotten_password_url' => 'string',
        'login_id_caption' => 'string',
        'password_caption' => 'string',
        'secondary_login_id_caption' => 'string',
        'security_code_caption' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'forgotten_password_url' => null,
        'login_id_caption' => null,
        'password_caption' => null,
        'secondary_login_id_caption' => null,
        'security_code_caption' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'forgotten_password_url' => false,
		'login_id_caption' => false,
		'password_caption' => false,
		'secondary_login_id_caption' => false,
		'security_code_caption' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'forgotten_password_url' => 'forgotten_password_url',
        'login_id_caption' => 'login_id_caption',
        'password_caption' => 'password_caption',
        'secondary_login_id_caption' => 'secondary_login_id_caption',
        'security_code_caption' => 'security_code_caption'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'forgotten_password_url' => 'setForgottenPasswordUrl',
        'login_id_caption' => 'setLoginIdCaption',
        'password_caption' => 'setPasswordCaption',
        'secondary_login_id_caption' => 'setSecondaryLoginIdCaption',
        'security_code_caption' => 'setSecurityCodeCaption'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'forgotten_password_url' => 'getForgottenPasswordUrl',
        'login_id_caption' => 'getLoginIdCaption',
        'password_caption' => 'getPasswordCaption',
        'secondary_login_id_caption' => 'getSecondaryLoginIdCaption',
        'security_code_caption' => 'getSecurityCodeCaption'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('forgotten_password_url', $data ?? [], null);
        $this->setIfExists('login_id_caption', $data ?? [], null);
        $this->setIfExists('password_caption', $data ?? [], null);
        $this->setIfExists('secondary_login_id_caption', $data ?? [], null);
        $this->setIfExists('security_code_caption', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets forgotten_password_url
     *
     * @return string|null
     */
    public function getForgottenPasswordUrl()
    {
        return $this->container['forgotten_password_url'];
    }

    /**
     * Sets forgotten_password_url
     *
     * @param string|null $forgotten_password_url URL to institution forgotten password page
     *
     * @return self
     */
    public function setForgottenPasswordUrl($forgotten_password_url)
    {
        if (is_null($forgotten_password_url)) {
            throw new \InvalidArgumentException('non-nullable forgotten_password_url cannot be null');
        }
        $this->container['forgotten_password_url'] = $forgotten_password_url;

        return $this;
    }

    /**
     * Gets login_id_caption
     *
     * @return string|null
     */
    public function getLoginIdCaption()
    {
        return $this->container['login_id_caption'];
    }

    /**
     * Sets login_id_caption
     *
     * @param string|null $login_id_caption Login ID field caption that should be shown on UI
     *
     * @return self
     */
    public function setLoginIdCaption($login_id_caption)
    {
        if (is_null($login_id_caption)) {
            throw new \InvalidArgumentException('non-nullable login_id_caption cannot be null');
        }
        $this->container['login_id_caption'] = $login_id_caption;

        return $this;
    }

    /**
     * Gets password_caption
     *
     * @return string|null
     */
    public function getPasswordCaption()
    {
        return $this->container['password_caption'];
    }

    /**
     * Sets password_caption
     *
     * @param string|null $password_caption Password field caption that should be shown on UI
     *
     * @return self
     */
    public function setPasswordCaption($password_caption)
    {
        if (is_null($password_caption)) {
            throw new \InvalidArgumentException('non-nullable password_caption cannot be null');
        }
        $this->container['password_caption'] = $password_caption;

        return $this;
    }

    /**
     * Gets secondary_login_id_caption
     *
     * @return string|null
     */
    public function getSecondaryLoginIdCaption()
    {
        return $this->container['secondary_login_id_caption'];
    }

    /**
     * Sets secondary_login_id_caption
     *
     * @param string|null $secondary_login_id_caption Secondary loginID caption that should be shown on UI
     *
     * @return self
     */
    public function setSecondaryLoginIdCaption($secondary_login_id_caption)
    {
        if (is_null($secondary_login_id_caption)) {
            throw new \InvalidArgumentException('non-nullable secondary_login_id_caption cannot be null');
        }
        $this->container['secondary_login_id_caption'] = $secondary_login_id_caption;

        return $this;
    }

    /**
     * Gets security_code_caption
     *
     * @return string|null
     */
    public function getSecurityCodeCaption()
    {
        return $this->container['security_code_caption'];
    }

    /**
     * Sets security_code_caption
     *
     * @param string|null $security_code_caption Security code caption that should be shown on UI
     *
     * @return self
     */
    public function setSecurityCodeCaption($security_code_caption)
    {
        if (is_null($security_code_caption)) {
            throw new \InvalidArgumentException('non-nullable security_code_caption cannot be null');
        }
        $this->container['security_code_caption'] = $security_code_caption;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


