<?php
/**
 * InstitutionPerformanceStatsAverageDurationMs
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Core
 *
 * All included utility endpoints for Basiq partners
 *
 * The version of the OpenAPI document: 3.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * InstitutionPerformanceStatsAverageDurationMs Class Doc Comment
 *
 * @category Class
 * @description AverageDurationMs average connector duration in milliseconds per segments. When durations are not known for institution this field will be &#x60;null&#x60;.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class InstitutionPerformanceStatsAverageDurationMs implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'InstitutionPerformanceStats_averageDurationMs';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'retrieve_accounts' => 'int',
        'retrieve_meta' => 'int',
        'retrieve_transactions' => 'int',
        'total' => 'int',
        'verify_credentials' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'retrieve_accounts' => 'int64',
        'retrieve_meta' => 'int64',
        'retrieve_transactions' => 'int64',
        'total' => 'int64',
        'verify_credentials' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'retrieve_accounts' => false,
		'retrieve_meta' => false,
		'retrieve_transactions' => false,
		'total' => false,
		'verify_credentials' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'retrieve_accounts' => 'retrieveAccounts',
        'retrieve_meta' => 'retrieveMeta',
        'retrieve_transactions' => 'retrieveTransactions',
        'total' => 'total',
        'verify_credentials' => 'verifyCredentials'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'retrieve_accounts' => 'setRetrieveAccounts',
        'retrieve_meta' => 'setRetrieveMeta',
        'retrieve_transactions' => 'setRetrieveTransactions',
        'total' => 'setTotal',
        'verify_credentials' => 'setVerifyCredentials'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'retrieve_accounts' => 'getRetrieveAccounts',
        'retrieve_meta' => 'getRetrieveMeta',
        'retrieve_transactions' => 'getRetrieveTransactions',
        'total' => 'getTotal',
        'verify_credentials' => 'getVerifyCredentials'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('retrieve_accounts', $data ?? [], null);
        $this->setIfExists('retrieve_meta', $data ?? [], null);
        $this->setIfExists('retrieve_transactions', $data ?? [], null);
        $this->setIfExists('total', $data ?? [], null);
        $this->setIfExists('verify_credentials', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets retrieve_accounts
     *
     * @return int|null
     */
    public function getRetrieveAccounts()
    {
        return $this->container['retrieve_accounts'];
    }

    /**
     * Sets retrieve_accounts
     *
     * @param int|null $retrieve_accounts Connector average duration in milliseconds of <b>fetch accounts</b> step for institution
     *
     * @return self
     */
    public function setRetrieveAccounts($retrieve_accounts)
    {
        if (is_null($retrieve_accounts)) {
            throw new \InvalidArgumentException('non-nullable retrieve_accounts cannot be null');
        }
        $this->container['retrieve_accounts'] = $retrieve_accounts;

        return $this;
    }

    /**
     * Gets retrieve_meta
     *
     * @return int|null
     */
    public function getRetrieveMeta()
    {
        return $this->container['retrieve_meta'];
    }

    /**
     * Sets retrieve_meta
     *
     * @param int|null $retrieve_meta Connector average duration in milliseconds of <b>fetch metadata</b> step for institution
     *
     * @return self
     */
    public function setRetrieveMeta($retrieve_meta)
    {
        if (is_null($retrieve_meta)) {
            throw new \InvalidArgumentException('non-nullable retrieve_meta cannot be null');
        }
        $this->container['retrieve_meta'] = $retrieve_meta;

        return $this;
    }

    /**
     * Gets retrieve_transactions
     *
     * @return int|null
     */
    public function getRetrieveTransactions()
    {
        return $this->container['retrieve_transactions'];
    }

    /**
     * Sets retrieve_transactions
     *
     * @param int|null $retrieve_transactions Connector average duration in milliseconds of <b>fetch transactions</b> step for institution
     *
     * @return self
     */
    public function setRetrieveTransactions($retrieve_transactions)
    {
        if (is_null($retrieve_transactions)) {
            throw new \InvalidArgumentException('non-nullable retrieve_transactions cannot be null');
        }
        $this->container['retrieve_transactions'] = $retrieve_transactions;

        return $this;
    }

    /**
     * Gets total
     *
     * @return int|null
     */
    public function getTotal()
    {
        return $this->container['total'];
    }

    /**
     * Sets total
     *
     * @param int|null $total Total connector average duration in milliseconds
     *
     * @return self
     */
    public function setTotal($total)
    {
        if (is_null($total)) {
            throw new \InvalidArgumentException('non-nullable total cannot be null');
        }
        $this->container['total'] = $total;

        return $this;
    }

    /**
     * Gets verify_credentials
     *
     * @return int|null
     */
    public function getVerifyCredentials()
    {
        return $this->container['verify_credentials'];
    }

    /**
     * Sets verify_credentials
     *
     * @param int|null $verify_credentials Connector average duration in milliseconds of <b>verifiy credentials</b> step for institution
     *
     * @return self
     */
    public function setVerifyCredentials($verify_credentials)
    {
        if (is_null($verify_credentials)) {
            throw new \InvalidArgumentException('non-nullable verify_credentials cannot be null');
        }
        $this->container['verify_credentials'] = $verify_credentials;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


